name: Cloudshop CI

on:
  push:
    - main:

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm CI

      - name: Verify application syntax
        run: node --check src/server.js
