name: CloudShop Frontend CD

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-cd.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # ==========================================
      # 1. Checkout source code
      # ==========================================
      - name: Checkout repository
        uses: actions/checkout@v4


      # ==========================================
      # 2. Setup Node.js
      # ==========================================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json


      # ==========================================
      # 3. Install frontend dependencies
      # ==========================================
      - name: Install dependencies
        working-directory: frontend
        run: npm ci


      # ==========================================
      # 4. Build React/Vite frontend
      # ==========================================
      - name: Build frontend
        working-directory: frontend
        env:
          VITE_API_URL: https://api.tonghuynh.me
        run: npm run build


      # ==========================================
      # 5. Configure AWS credentials using OIDC
      # ==========================================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::610331149330:role/CloudShopGitHubActionsRole
          aws-region: ap-southeast-1


      # ==========================================
      # 6. Deploy build files to S3
      # ==========================================
      - name: Deploy frontend to S3
        run: |
          aws s3 sync frontend/dist/ \
            s3://cloudshop-frontend-610331149330 \
            --delete


      # ==========================================
      # 7. Clear CloudFront cache
      # ==========================================
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E3FRXWDXGURTWO \
            --paths "/*"